# Generated by Django 3.2.9 on 2021-12-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0002_auto_20211202_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
