# Generated by Django 3.2.9 on 2021-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0003_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='breaking_strength',
        ),
        migrations.AlterField(
            model_name='material',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='electric_conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='hardness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat_resistance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_class',
            field=models.CharField(choices=[('Holz', 'Holz'), ('Kunststoff', 'Kunststoff'), ('Metall', 'Metall')], default='Holz', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tensile_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='water_cunsumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
