# Generated by Django 3.2.9 on 2021-12-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0004_auto_20211212_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='heat_resistance',
            new_name='heat_conductivity',
        ),
    ]
