# Generated by Django 3.2.9 on 2021-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0005_rename_heat_resistance_material_heat_conductivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='heat_resistance',
            new_name='heat_conductivity',
        ),
    ]
