# Generated by Django 3.2.9 on 2021-12-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0006_rename_heat_resistance_usecase_heat_conductivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='breaking_strength',
        ),
    ]
