# Generated by Django 3.2.9 on 2021-12-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0007_remove_usecase_breaking_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_class',
            field=models.CharField(choices=[('Holz', 'Holz'), ('Polymer', 'Polymer'), ('Leichtmetall', 'Leichtmetall'), ('Schwermetall', 'Schwermetall'), ('Stahl', 'Stahl'), ('Verbundwerkstoff', 'Verbundwerkstoff'), ('Glas', 'Glas')], default='Holz', max_length=200),
        ),
    ]
