# Generated by Django 3.2.9 on 2022-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0008_alter_material_material_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=50)),
                ('Subject', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
