# Generated by Django 3.2.9 on 2022-01-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0009_contactmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactMessage',
        ),
    ]
