# Generated by Django 3.2.9 on 2022-01-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0010_rename_contactmessages_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='Description',
            new_name='Beschreibung',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='Subject',
            new_name='Titel',
        ),
    ]
