# Generated by Django 4.0.1 on 2022-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0011_auto_20220109_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='density',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='electric_conductivity',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='hardness',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='heat_capacity',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='heat_conductivity',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='tensile_strength',
        ),
        migrations.AddField(
            model_name='usecase',
            name='density_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='density_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='electric_conductivity_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='electric_conductivity_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='hardness_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='hardness_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='heat_capacity_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='heat_capacity_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='heat_conductivity_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='heat_conductivity_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='tensile_strength_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='tensile_strength_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='Beschreibung',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Aufgegeben'), ('2', 'In Bearbeitung'), ('3', 'Abgeschlossen')], default='Aufgegeben', max_length=50),
        ),
    ]
