# Generated by Django 4.0.1 on 2022-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webShop', '0012_remove_usecase_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='density_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='density_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='electric_conductivity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='electric_conductivity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='hardness_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='hardness_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='heat_capacity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='heat_capacity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='heat_conductivity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='heat_conductivity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='tensile_strength_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='tensile_strength_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
